name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: mvn --batch-mode --update-snapshots package
      - uses: burnett01/rsync-deployments@5.2
        with:
          switches: -havz
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          remote_port: ${{ secrets.SERVER_PORT }}
          path: "target/quotes.jar"
          remote_path: "/home/quotes/app/quotes.jar"
      - name: restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: systemctl --user restart quotes.service
